### ISSUE TITLE
yuiman_workshopをOrganization mottanProjectに委譲したい

### ISSUE THREAD

**Issue by y4ml** [mottanCopen/yuiman_workshop#2]
mottanCopen配下にあるとy4mlが操作できる権限が限られているためOrganization配下に移動させる

https://github.com/mottanProject

- やり方
    - https://docs.github.com/ja/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations

**Comment by mottanCopen** [comment]
手順通り対応しましたがいかがでしょうか

**Comment by y4ml** [comment]
y4mlが移動させたのでclose
